<?php

/**
 * MatchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MatchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MatchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Match');
    }
}