<?php

/**
 * PlayingFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayingFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayingFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlayingField');
    }
}