<?php

/**
 * PlayingFieldRentalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayingFieldRentalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayingFieldRentalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlayingFieldRental');
    }
}