<?php

/**
 * RentalDisciplineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RentalDisciplineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RentalDisciplineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RentalDiscipline');
    }
}