<?php

/**
 * TeamPlayerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamPlayerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamPlayerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamPlayer');
    }
}