<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/23 20:06:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tp-taller',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
