<?php

/**
 * BaseDiscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Rentals
 * @property Doctrine_Collection $Matches
 * @property Doctrine_Collection $Teams
 * @property Doctrine_Collection $RentalDisciplines
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method Doctrine_Collection getRentals()           Returns the current record's "Rentals" collection
 * @method Doctrine_Collection getMatches()           Returns the current record's "Matches" collection
 * @method Doctrine_Collection getTeams()             Returns the current record's "Teams" collection
 * @method Doctrine_Collection getRentalDisciplines() Returns the current record's "RentalDisciplines" collection
 * @method Discipline          setName()              Sets the current record's "name" value
 * @method Discipline          setRentals()           Sets the current record's "Rentals" collection
 * @method Discipline          setMatches()           Sets the current record's "Matches" collection
 * @method Discipline          setTeams()             Sets the current record's "Teams" collection
 * @method Discipline          setRentalDisciplines() Sets the current record's "RentalDisciplines" collection
 * 
 * @package    tp-taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiscipline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('discipline');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PlayingFieldRental as Rentals', array(
             'refClass' => 'RentalDiscipline',
             'local' => 'discipline_id',
             'foreign' => 'rental_id'));

        $this->hasMany('Match as Matches', array(
             'local' => 'id',
             'foreign' => 'discipline_id'));

        $this->hasMany('Team as Teams', array(
             'local' => 'id',
             'foreign' => 'discipline_id'));

        $this->hasMany('RentalDiscipline as RentalDisciplines', array(
             'local' => 'id',
             'foreign' => 'discipline_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}