<?php

/**
 * BaseMatchPlayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $match_id
 * @property integer $player_id
 * @property Match $Match
 * @property sfGuardUser $Player
 * 
 * @method integer     getMatchId()   Returns the current record's "match_id" value
 * @method integer     getPlayerId()  Returns the current record's "player_id" value
 * @method Match       getMatch()     Returns the current record's "Match" value
 * @method sfGuardUser getPlayer()    Returns the current record's "Player" value
 * @method MatchPlayer setMatchId()   Sets the current record's "match_id" value
 * @method MatchPlayer setPlayerId()  Sets the current record's "player_id" value
 * @method MatchPlayer setMatch()     Sets the current record's "Match" value
 * @method MatchPlayer setPlayer()    Sets the current record's "Player" value
 * 
 * @package    tp-taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMatchPlayer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('match_player');
        $this->hasColumn('match_id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('player_id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Match', array(
             'local' => 'match_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Player', array(
             'local' => 'player_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}