<?php

/**
 * BasePlayingField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $address
 * @property string $city
 * @property string $province
 * @property string $country
 * @property string $phoneNo
 * @property string $type
 * @property Doctrine_Collection $HeldMatches
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getAddress()     Returns the current record's "address" value
 * @method string              getCity()        Returns the current record's "city" value
 * @method string              getProvince()    Returns the current record's "province" value
 * @method string              getCountry()     Returns the current record's "country" value
 * @method string              getPhoneNo()     Returns the current record's "phoneNo" value
 * @method string              getType()        Returns the current record's "type" value
 * @method Doctrine_Collection getHeldMatches() Returns the current record's "HeldMatches" collection
 * @method PlayingField        setName()        Sets the current record's "name" value
 * @method PlayingField        setAddress()     Sets the current record's "address" value
 * @method PlayingField        setCity()        Sets the current record's "city" value
 * @method PlayingField        setProvince()    Sets the current record's "province" value
 * @method PlayingField        setCountry()     Sets the current record's "country" value
 * @method PlayingField        setPhoneNo()     Sets the current record's "phoneNo" value
 * @method PlayingField        setType()        Sets the current record's "type" value
 * @method PlayingField        setHeldMatches() Sets the current record's "HeldMatches" collection
 * 
 * @package    tp-taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayingField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('playing_field');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('province', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phoneNo', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'PlayingFieldRental' => 
             array(
              'type' => 'PlayingFieldRental',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Match as HeldMatches', array(
             'local' => 'id',
             'foreign' => 'playing_field_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}