<?php

/**
 * BaseTenantDiscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tenant_id
 * @property integer $discipline_id
 * @property PlayingFieldTenant $PlayingFieldTenant
 * @property Discipline $Discipline
 * 
 * @method integer            getTenantId()           Returns the current record's "tenant_id" value
 * @method integer            getDisciplineId()       Returns the current record's "discipline_id" value
 * @method PlayingFieldTenant getPlayingFieldTenant() Returns the current record's "PlayingFieldTenant" value
 * @method Discipline         getDiscipline()         Returns the current record's "Discipline" value
 * @method TenantDiscipline   setTenantId()           Sets the current record's "tenant_id" value
 * @method TenantDiscipline   setDisciplineId()       Sets the current record's "discipline_id" value
 * @method TenantDiscipline   setPlayingFieldTenant() Sets the current record's "PlayingFieldTenant" value
 * @method TenantDiscipline   setDiscipline()         Sets the current record's "Discipline" value
 * 
 * @package    tp-taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTenantDiscipline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tenant_discipline');
        $this->hasColumn('tenant_id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('discipline_id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PlayingFieldTenant', array(
             'local' => 'tenant_id',
             'foreign' => 'id'));

        $this->hasOne('Discipline', array(
             'local' => 'discipline_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}