<?php

/**
 * BasePlayingFieldTenant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Disciplines
 * @property Doctrine_Collection $TenantDisciplines
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method Doctrine_Collection getDisciplines()       Returns the current record's "Disciplines" collection
 * @method Doctrine_Collection getTenantDisciplines() Returns the current record's "TenantDisciplines" collection
 * @method PlayingFieldTenant  setName()              Sets the current record's "name" value
 * @method PlayingFieldTenant  setDisciplines()       Sets the current record's "Disciplines" collection
 * @method PlayingFieldTenant  setTenantDisciplines() Sets the current record's "TenantDisciplines" collection
 * 
 * @package    tp-taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayingFieldTenant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('playing_field_tenant');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Discipline as Disciplines', array(
             'refClass' => 'TenantDiscipline',
             'local' => 'tenant_id',
             'foreign' => 'discipline_id'));

        $this->hasMany('TenantDiscipline as TenantDisciplines', array(
             'local' => 'id',
             'foreign' => 'tenant_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}