<?php

/**
 * BaseRentalDiscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rental_id
 * @property integer $discipline_id
 * @property PlayingFieldRental $PlayingFieldRental
 * @property Discipline $Discipline
 * 
 * @method integer            getRentalId()           Returns the current record's "rental_id" value
 * @method integer            getDisciplineId()       Returns the current record's "discipline_id" value
 * @method PlayingFieldRental getPlayingFieldRental() Returns the current record's "PlayingFieldRental" value
 * @method Discipline         getDiscipline()         Returns the current record's "Discipline" value
 * @method RentalDiscipline   setRentalId()           Sets the current record's "rental_id" value
 * @method RentalDiscipline   setDisciplineId()       Sets the current record's "discipline_id" value
 * @method RentalDiscipline   setPlayingFieldRental() Sets the current record's "PlayingFieldRental" value
 * @method RentalDiscipline   setDiscipline()         Sets the current record's "Discipline" value
 * 
 * @package    tp-taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRentalDiscipline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rental_discipline');
        $this->hasColumn('rental_id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('discipline_id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PlayingFieldRental', array(
             'local' => 'rental_id',
             'foreign' => 'id'));

        $this->hasOne('Discipline', array(
             'local' => 'discipline_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}