<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $discipline_id
 * @property Doctrine_Collection $Players
 * @property Discipline $Discipline
 * @property Doctrine_Collection $HeldMatches
 * @property Doctrine_Collection $TeamPlayers
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getDisciplineId()  Returns the current record's "discipline_id" value
 * @method Doctrine_Collection getPlayers()       Returns the current record's "Players" collection
 * @method Discipline          getDiscipline()    Returns the current record's "Discipline" value
 * @method Doctrine_Collection getHeldMatches()   Returns the current record's "HeldMatches" collection
 * @method Doctrine_Collection getTeamPlayers()   Returns the current record's "TeamPlayers" collection
 * @method Team                setName()          Sets the current record's "name" value
 * @method Team                setDisciplineId()  Sets the current record's "discipline_id" value
 * @method Team                setPlayers()       Sets the current record's "Players" collection
 * @method Team                setDiscipline()    Sets the current record's "Discipline" value
 * @method Team                setHeldMatches()   Sets the current record's "HeldMatches" collection
 * @method Team                setTeamPlayers()   Sets the current record's "TeamPlayers" collection
 * 
 * @package    tp-taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('discipline_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUserProfile as Players', array(
             'refClass' => 'TeamPlayer',
             'local' => 'team_id',
             'foreign' => 'player_id'));

        $this->hasOne('Discipline', array(
             'local' => 'discipline_id',
             'foreign' => 'id'));

        $this->hasMany('Match as HeldMatches', array(
             'local' => 'id',
             'foreign' => 'local_id'));

        $this->hasMany('TeamPlayer as TeamPlayers', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}