<?php

/**
 * BasePlayingFieldRental
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Disciplines
 * @property Doctrine_Collection $RentalDisciplines
 * 
 * @method Doctrine_Collection getDisciplines()       Returns the current record's "Disciplines" collection
 * @method Doctrine_Collection getRentalDisciplines() Returns the current record's "RentalDisciplines" collection
 * @method PlayingFieldRental  setDisciplines()       Sets the current record's "Disciplines" collection
 * @method PlayingFieldRental  setRentalDisciplines() Sets the current record's "RentalDisciplines" collection
 * 
 * @package    tp-taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayingFieldRental extends PlayingField
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Discipline as Disciplines', array(
             'refClass' => 'RentalDiscipline',
             'local' => 'rental_id',
             'foreign' => 'discipline_id'));

        $this->hasMany('RentalDiscipline as RentalDisciplines', array(
             'local' => 'id',
             'foreign' => 'rental_id'));
    }
}