<?php

/**
 * PlayingFieldTenantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayingFieldTenantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayingFieldTenantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlayingFieldTenant');
    }
}