<?php

/**
 * TenantDisciplineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TenantDisciplineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TenantDisciplineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TenantDiscipline');
    }
}